conf:
  ums:
    sys:
      #系统名称
      title: 临床试验项目信息管理
      #logo配置 用当前应用机构缩写 例如:儿童医院 -> etyy
      logo: logo-wh.png
      #内部页面logo
      logoMenu: logo-menu-wh.png
      #标签页图标ico
      logoIco: logo-wh.ico
      #登录页下方的申康标记
      tab:
      #主题
      theme: darkblue
    ip: 192.168.1.27
    port: 8900
spring:
  datasource:
    url: jdbc:mysql://192.168.1.27:3306/sz?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: 142536
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 5
    min-idle: 5
    max-active: 20
    # 配置获取连接等待超时的时间
    max-wait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 90000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000
    #thymeleaf模板配置
    thymeleaf:
      cache: false                   # 这个开发配置为false，避免改了模板还要重启服务器
      prefix: classpath:/templates/  #模板文件视图前缀，默认是classpath:/templates/，可不用配置
      suffix: .html                  #模板文件视图后缀，默认是.html，可不用配置
      check-template-location: true  #检查模板位置，可不用配置
      encoding: utf-8                #编码字符集，默认为utf-8，可不用配置
      mode: HTML                     #模板的模式，默认为HTML，可不用配置
      servlet:
        content-type: text/html       #模板的内容类型，默认为text/html，可不用配置
  jpa:
    hibernate:
      #     更新或者创建数据表结构
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #    控制台显示SQL
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
server:
  port: ${conf.ums.port:8900}
  servlet:
    context-path: /ums
  max-http-header-size: 102400
sysCode:
  value: 100